accounts/urls.py
from django.urls import path
from . import views
from .views import logout_view

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
]

projects/urls.py
from django.urls import path
from projects.views import project_list, show_project, create_project
from django.contrib.auth import views as auth_views


app_name = 'projects'

urlpatterns = [
    path('', project_list, name='list_projects'),
    path('<int:id>/', show_project, name='show_project'),
    path('create/', create_project, name='create_project'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
]

tracker/urls.py
from django.contrib import admin
from django.urls import include, path
from projects.views import project_list
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(pattern_name='project-list'), name='home'),
    path('projects/', project_list, name='project-list'),
    path("admin/", admin.site.urls),
    path('projects/', include('projects.urls')),
    path('projects/', project_list, name='list_projects')

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

projects/models.py
from django.db import models
from django import forms


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(default='')
    owner = models.ForeignKey(
        "auth.User",
        related_name="projects",
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return self.name


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'owner']

tasks/models.py
from django.db import models
from projects.models import Project
from django.contrib.auth.models import User


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(Project, related_name="tasks", on_delete=models.CASCADE)
    assignee = models.ForeignKey(User, null=True, related_name="tasks", on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)


class SignupForm(UserCreationForm):
    password_confirmation = forms.CharField(
        label='Confirm Password',
        widget=forms.PasswordInput,
        max_length=150
    )


class Meta(UserCreationForm.Meta):
    fields = ['username', 'password1', 'password2', 'password_confirmation']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from accounts.forms import LoginForm
from django.contrib.auth.decorators import login_required
from .models import Project
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm


@login_required
def project_list(request):
    projects = Project.objects.filter(owner=request.user)
    context = {'projects': projects}
    return render(request, 'accounts/project_list.html', context)


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('project-list')
    else:
        form = LoginForm()

    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect(reverse('login'))


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data.get('password1')
            user = form.save()
            user = authenticate(username=user.username, password=password)
            login(request, user)
            return redirect('project_list')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from projects.models import Project, ProjectForm


@login_required
def project_list(request):
    projects = Project.objects.all()
    context = {
        'projects': projects
    }
    return render(request, 'projects/project_list.html', context)


@login_required
def show_project(request, id):
    project = get_object_or_404(Project, id=id)
    context = {'project': project}
    return render(request, 'projects/project_detail.html', context)


@login_required
def create_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('projects:list_projects')
    else:
        form = ProjectForm()
    context = {'form': form}
    return render(request, 'projects/create_project.html', context)

tasks/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
<head>
  <title>Login</title>
</head>
<body>
  <main>
    <div>
      <h1>Login</h1>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
      </form>
    </div>
  </main>
</body>
</html>

projects/templates/projects/create_project.html
<!DOCTYPE html>
<html>
    <head>
        <title>Create Project</title>
    </head>
    <body>
        <main>
            <div>
                <h1>Create a new project</h1>
                <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                    <button type="submit">Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

projects/templates/projects/project_detail.html
<!DOCTYPE HTML>
  <main>
    <div>
      <h1>{{ project.name }}</h1>
      <p>{{ project.description }}</p>
      <h2>Tasks</h2>
      {% if project.tasks.exists %}
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Assignee</th>
              <th>Start date</th>
              <th>Due date</th>
              <th>Is completed</th>
            </tr>
          </thead>
          <tbody>
            {% for task in project.tasks.all %}
              <tr>
                <td>{{ task.name }}</td>
                <td>{{ task.assignee.username }}</td>
                <td>{{ task.start_date }}</td>
                <td>{{ task.due_date }}</td>
                <td>{{ task.is_completed|yesno:"yes,no" }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      {% else %}
        <p>This project has no tasks</p>
      {% endif %}
    </div>
  </main>
</HTML>

projects/templates/projects/project_list.html
<!DOCTYPE html>
<html>
<head>
  <title>My Projects</title>
</head>
<body>
  <main>
    <div>
      <h1>My Projects</h1>
      <p>
        <a href="{% url 'projects:create_project' %}">Create a new project</a>
      </p>
      {% if projects %}
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>Number of tasks</th>
            </tr>
          </thead>
          <tbody>
            {% for project in projects %}
              <tr>
                <td>{{ project.name }}</td>
                <td></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      {% else %}
        <p>You are not assigned to any projects</p>
      {% endif %}
    </div>
  </main>
</body>
</html>